management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/microservices_training
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
