/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import com.formdev.flatlaf.FlatDarkLaf;
import java.awt.Color;
import java.awt.Graphics;
import java.awt.Image;
import java.io.IOException;
import java.util.EmptyStackException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import model.Tree;

/**
 *
 * @author HASHA
 */
public class ChristmasTree extends javax.swing.JFrame {

    /**
     * Creates new form ChristmasTree
     */
    Tree tree;

    public ChristmasTree() {
        initComponents();
        tree = new Tree();
        Image i;
        try {
            i = ImageIO.read(getClass().getResource("/resources/deco_red.png"));
            setIconImage(i);
            setTitle("Christmas Tree Decorater");
        } catch (IOException ex) {
            Logger.getLogger(ChristmasTree.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        christmasTree = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Golden = new javax.swing.JLabel();
        Golden1 = new javax.swing.JLabel();
        Red = new javax.swing.JLabel();
        Golden3 = new javax.swing.JLabel();
        Golden4 = new javax.swing.JLabel();
        Golden5 = new javax.swing.JLabel();
        blueRadio = new javax.swing.JRadioButton();
        decoRedRadio = new javax.swing.JRadioButton();
        goldRadio = new javax.swing.JRadioButton();
        redRadio = new javax.swing.JRadioButton();
        yelloRadio = new javax.swing.JRadioButton();
        silverRadio = new javax.swing.JRadioButton();
        bellRadio = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        christmasTree.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        christmasTree.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/christmas-tree-christmas-1796131_640-578x624.png"))); // NOI18N
        christmasTree.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                christmasTreeMouseClicked(evt);
            }
        });
        getContentPane().add(christmasTree, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 40, 580, -1));

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        getContentPane().add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 30, 80));

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/deco_red.png"))); // NOI18N
        jLabel1.setText("Decorated Red");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });

        Golden.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/gold.png"))); // NOI18N
        Golden.setText("Gold");
        Golden.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoldenMouseClicked(evt);
            }
        });

        Golden1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/blue.png"))); // NOI18N
        Golden1.setText("Blue");
        Golden1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Golden1MouseClicked(evt);
            }
        });

        Red.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/red.png"))); // NOI18N
        Red.setText("Red");
        Red.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                RedMouseClicked(evt);
            }
        });

        Golden3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/yellow.png"))); // NOI18N
        Golden3.setText("Yellow");
        Golden3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Golden3MouseClicked(evt);
            }
        });

        Golden4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/silver.png"))); // NOI18N
        Golden4.setText("Silver");
        Golden4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Golden4MouseClicked(evt);
            }
        });

        Golden5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/bell.png"))); // NOI18N
        Golden5.setText("Bell");
        Golden5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Golden5MouseClicked(evt);
            }
        });

        buttonGroup1.add(blueRadio);
        blueRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(decoRedRadio);
        decoRedRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                none(evt);
            }
        });

        buttonGroup1.add(goldRadio);
        goldRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                goldRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(redRadio);
        redRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(yelloRadio);
        yelloRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yelloRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(silverRadio);
        silverRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silverRadioActionPerformed(evt);
            }
        });

        buttonGroup1.add(bellRadio);
        bellRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bellRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 135, Short.MAX_VALUE)
                    .addComponent(Golden5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Golden4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Golden3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Red, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Golden1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Golden, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(decoRedRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(goldRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(redRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yelloRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(silverRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bellRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(decoRedRadio)))
                .addGap(6, 6, 6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Golden)
                    .addComponent(goldRadio, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Golden1)
                    .addComponent(blueRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Red)
                    .addComponent(redRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Golden3)
                    .addComponent(yelloRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Golden4)
                    .addComponent(silverRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Golden5)
                    .addComponent(bellRadio))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 40, 210, 470));

        jButton1.setText("Undo");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 530, 210, -1));

        jLabel2.setText("Decorations");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel3.setText("Christmas Tree");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, 120, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/frame.png"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 120, 10));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 20, 120, 10));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void christmasTreeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_christmasTreeMouseClicked
            
        if (image == null) {
            JOptionPane.showMessageDialog(this, "Select a Decoration");
        } else if (!isInside(0, 624,(578 / 2),0, 578, 624, evt.getX(), evt.getY())) {
            JOptionPane.showMessageDialog(this, "Outside the tree");
        } else {
            JLabel l = new JLabel();
            l.setIcon(image);
            l.setLocation(evt.getX() - 15, evt.getY());
            l.setSize(60, 60);
            tree.save(l);

            christmasTree.add(l);
            christmasTree.revalidate();
            christmasTree.repaint();
        }


    }//GEN-LAST:event_christmasTreeMouseClicked
    ImageIcon image;
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        image = new ImageIcon(getClass().getResource("/resources/deco_red.png"));
        decoRedRadio.setSelected(true);

    }//GEN-LAST:event_jLabel1MouseClicked

    private void GoldenMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoldenMouseClicked
        image = new ImageIcon(getClass().getResource("/resources/gold.png"));
        goldRadio.setSelected(true);
    }//GEN-LAST:event_GoldenMouseClicked

    private void Golden1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Golden1MouseClicked
        image = new ImageIcon(getClass().getResource("/resources/blue.png"));
        blueRadio.setSelected(true);
    }//GEN-LAST:event_Golden1MouseClicked

    private void RedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RedMouseClicked
        image = new ImageIcon(getClass().getResource("/resources/red.png"));
        redRadio.setSelected(true);
    }//GEN-LAST:event_RedMouseClicked

    private void Golden3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Golden3MouseClicked
        image = new ImageIcon(getClass().getResource("/resources/yellow.png"));
        yelloRadio.setSelected(true);
    }//GEN-LAST:event_Golden3MouseClicked

    private void Golden4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Golden4MouseClicked
        image = new ImageIcon(getClass().getResource("/resources/silver.png"));
        silverRadio.setSelected(true);
    }//GEN-LAST:event_Golden4MouseClicked

    private void Golden5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Golden5MouseClicked
        image = new ImageIcon(getClass().getResource("/resources/bell.png"));
        bellRadio.setSelected(true);
    }//GEN-LAST:event_Golden5MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            tree.undo();
            christmasTree.remove(tree.getDecorationLabel());
            christmasTree.revalidate();
            christmasTree.repaint();
        } catch (EmptyStackException e) {
          JOptionPane.showMessageDialog(this, "Nothing to UNDO");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void blueRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueRadioActionPerformed

    private void none(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_none
        // TODO add your handling code here:
    }//GEN-LAST:event_none

    private void goldRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_goldRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_goldRadioActionPerformed

    private void redRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_redRadioActionPerformed

    private void yelloRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yelloRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_yelloRadioActionPerformed

    private void silverRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silverRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_silverRadioActionPerformed

    private void bellRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bellRadioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bellRadioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            UIManager.setLookAndFeel(new FlatDarkLaf()); //</editor-fold>
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChristmasTree.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChristmasTree().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Golden;
    private javax.swing.JLabel Golden1;
    private javax.swing.JLabel Golden3;
    private javax.swing.JLabel Golden4;
    private javax.swing.JLabel Golden5;
    private javax.swing.JLabel Red;
    private javax.swing.JRadioButton bellRadio;
    private javax.swing.JRadioButton blueRadio;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel christmasTree;
    private javax.swing.JRadioButton decoRedRadio;
    private javax.swing.JRadioButton goldRadio;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JRadioButton redRadio;
    private javax.swing.JRadioButton silverRadio;
    private javax.swing.JRadioButton yelloRadio;
    // End of variables declaration//GEN-END:variables

    static double area(int x1, int y1, int x2, int y2, int x3, int y3) {
        return Math.abs((x1 * (y2 - y3) + x2 * (y3 - y1) + x3 * (y1 - y2)) / 2.0);
    }
//else if (!isInside(0, 0, 578, 0, (578 / 2), 624, evt.getX(), evt.getY())) {
    static boolean isInside(int x1, int y1, int x2, int y2, int x3, int y3, int x, int y) {

        double A = area(x1, y1, x2, y2, x3, y3);

        double A1 = area(x, y, x2, y2, x3, y3);

        double A2 = area(x1, y1, x, y, x3, y3);

        double A3 = area(x1, y1, x2, y2, x, y);

        return (A == A1 + A2 + A3);
    }

}
