server:
  port: 9090
spring:
  security:
    user:
      name: hashan
      password: 1234
      roles: ADMIN,USER

security:
  oauth2:
    client:
      client-id: mobile
      client-secret: pin
      access-token-validity-seconds: 4000
      authorized-grant-types: refresh_token,authorization_code,password,client_credentials
      scope: READ,WRITE
