server:
  port: 8282

management:
  endpoints:
    web:
      exposure:
        include: "*"
spring:
  datasource:
    #Url of Already created Database
    #url: jdbc:mysql://localhost:3306/microservices_training2

    #Create new Database if given database not exist
    url: jdbc:mysql://localhost:3306/microservices_training2?createDatabaseIfNotExist=true
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver

#Variable names of Entities map to table column names
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#'ddl-auto: create' ->drop exist tables, create tables to entities when the start/run
#'ddl-auto: create-drop' ->drop exist tables, create tables to entities when the start/run and drop those tables after end or stop run
#'ddl-auto: update' -> create new tables if table not exist,otherwise exist tables remains when the start/run
      ddl-auto: update
