server:
  port: 8181
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Hashan1999/spring-cloud-config-store
          username: ********
          password: *******
          search-paths:
            - '*service'